# Enable anonymous metrics data? Please do, it helps us stay motivated.
metrics: true

# Sends a level up message to the player or as a broadcast.
level_up:
  enabled: true
  message: '&7[&3Island Rankup&7] &f<PLAYER>''s new rank is <RANK>'
  broadcast_mode: true

# Should ranks only apply to the world the player is in?
world_specific: false

# You can change these ranks or add to it if you would like, just make sure you follow the format.
ranks:
  dirt:
    start: 0
    end: 14
  grass:
    start: 15
    end: 29
  stone:
    start: 30
    end: 59
  iron:
    start: 60
    end: 124
  gold:
    start: 125
    end: 249
  obsidian:
    start: 250
    end: 499
  diamond:
    start: 500
    end: 999
  emerald:
    start: 1000
    end: 4999